#!/usr/bin/env python3
"""docx -> markdown, for the handbook audit trail.

The Portuguese source is .pages, which git cannot diff. Pages exports .docx,
and this renders that to markdown so a governance change shows up as a
readable diff rather than a changed binary.

Heading level is inferred from the run size Pages emits, since the export
carries no named heading styles:
    24pt  -> #      18pt -> ##      14pt -> ###      else body
"""
import sys, re, docx
from docx.oxml.ns import qn

H1, H2, H3 = 304800, 228600, 177800     # EMU


def is_bullet(p):
    # Pages puts numbering directly on the paragraph. python-docx (our own
    # md2docx.py) carries it on the named style instead, so a document
    # generated by this repo would otherwise round-trip with its bullets
    # flattened into paragraphs — checked on 2026-08-20, and it did.
    pPr = p._p.pPr
    if pPr is not None and pPr.find(qn('w:numPr')) is not None:
        return True
    return (p.style is not None
            and p.style.name in ("List Bullet", "List Number", "List Paragraph"))


def is_numbered(p):
    return p.style is not None and p.style.name == "List Number"


def inline(p):
    """Paragraph text with ** and * markers restored from the runs.

    Reading p.text throws inline formatting away. In a governance document
    that is not cosmetic: emphasis marks the defined terms, and a document
    brought back from .docx would lose every one of them silently.

    Adjacent runs of the same weight are merged first, because Word splits a
    single emphasised phrase across several runs whenever a spell-check or
    language boundary falls inside it — marking each one separately would
    produce `**A** **B**` where the document says `**A B**`.
    """
    merged = []
    for r in p.runs:
        if not r.text:
            continue
        weight = (bool(r.bold), bool(r.italic))
        if merged and merged[-1][0] == weight:
            merged[-1][1] += r.text
        else:
            merged.append([weight, r.text])

    parts = []
    for (bold, italic), text in merged:
        lead = len(text) - len(text.lstrip())
        trail = len(text) - len(text.rstrip())
        pre, core, post = text[:lead], text[lead:len(text) - trail or None], text[len(text) - trail:] if trail else ""
        if not core:
            parts.append(text)
            continue
        if bold:
            core = f"**{core}**"
        elif italic:
            core = f"*{core}*"
        parts.append(pre + core + post)
    return "".join(parts).strip()


def unwrap(text):
    """Drop a ** wrapper spanning the whole string.

    Headings are bold runs, so inline() marks them up like any other bold
    text. `# **Purpose**` is not wrong, but it is noise in a heading and it
    breaks the byte-identical round trip the parity check relies on.
    """
    return text[2:-2].strip() if text.startswith("**") and text.endswith("**") else text


def blocks(doc):
    """Paragraphs and tables, in the order the document actually has them.

    doc.paragraphs skips tables entirely, so a table was silently dropped on
    the way back to markdown — found on 2026-08-20, when doc 04 gained one
    and round-tripped six rows shorter. Walking the body element is the only
    way to keep the two interleaved correctly.
    """
    from docx.table import Table
    from docx.text.paragraph import Paragraph
    for child in doc.element.body.iterchildren():
        if child.tag == qn('w:p'):
            yield Paragraph(child, doc)
        elif child.tag == qn('w:tbl'):
            yield Table(child, doc)


def render_table(t):
    rows = []
    for row in t.rows:
        rows.append([unwrap(" ".join(inline(p) for p in cell.paragraphs).strip())
                     for cell in row.cells])
    if not rows:
        return []
    width = len(rows[0])
    out = ["| " + " | ".join(rows[0]) + " |", "|" + "---|" * width]
    for row in rows[1:]:
        out.append("| " + " | ".join(row) + " |")
    out.append("")
    return out


def convert(path):
    d = docx.Document(path)
    out, blank = [], False
    for block in blocks(d):
        if not hasattr(block, "runs"):          # a table
            blank = False
            out += render_table(block)
            continue
        p = block
        text = inline(p)
        if not text:
            if not blank and out:
                out.append(""); blank = True
            continue
        blank = False
        run = p.runs[0] if p.runs else None
        size = run.font.size if run else None

        if is_numbered(p):
            # Restart at 1. for each run of numbered items.
            prev = out[-1] if out else ""
            n = int(prev.split(".")[0]) + 1 if re.match(r"^\d+\. ", prev) else 1
            out.append(f"{n}. {text}")
        elif is_bullet(p):
            out.append(f"- {text}")          # list items stay adjacent
        elif size == H1:
            out += ([""] if out else []) + [f"# {unwrap(text)}", ""]
        elif size == H2:
            out += ([""] if out else []) + [f"## {unwrap(text)}", ""]
        elif size == H3:
            out += ([""] if out else []) + [f"### {unwrap(text)}", ""]
        # No bold branch here on purpose. inline() has already emitted the
        # ** markers for every bold run, so a whole-paragraph-bold rule
        # would wrap an already-wrapped string — which is what produced
        # `****Regeneration** — ...**` before 2026-08-20.
        else:
            out += [text, ""]      # blank line after every paragraph: markdown
                                   # needs it, and it makes each paragraph its
                                   # own diff hunk

    md = "\n".join(out)
    md = re.sub(r"\n{3,}", "\n\n", md).strip() + "\n"
    return md


if __name__ == '__main__':
    sys.stdout.write(convert(sys.argv[1]))
